<template>
  <div class="b-tos">
    <h1 class="b-h1">Quwi Terms of Service</h1>

    <h2 class="b-h2">About Us</h2>
    <p>Quwi is an incredibly intuitive online task management tool that runs inside your browser.</p>
    <p>The web app is complemented by our free task management app for Android, which makes sure that you stay productive even on the go.</p>
    <p>With its powerful collaboration features, the task management software lets you and your team manage projects easily.</p>
    <p>It keeps you up to date on your teammates’ progress while making sure that you never lose focus of your own to-dos or miss an important deadline.</p>
    <p>Quwi is more than a simple task management tool: it is a place where all your project related information is safely stored, yet accessible for all project members at all times; it’s a place where you can get insights into your own and your team’s productivity, and what’s more, it’s a place where work can be fun.</p>

    <h2 class="b-h2">Terms and Conditions of Use</h2>
    <p>We have taken every effort to design our Web site to be useful, informative, helpful, honest and fun. Hopefully we’ve accomplished that — and would ask that you let us know if you’d like to see improvements or changes that would make it even easier for you to find the information you need and want. All we ask is that you agree to abide by the following Terms and Conditions. Take a few minutes to look them over because by using our site you automatically agree to them. Naturally, if you don’t agree, please do not use the site. We reserve the right to make any modifications that we deem necessary at any time. Please continue to check these terms to see what those changes may be! Your continued use of the Udimicom, Limited. Web site means that you accept those changes.</p>
    <p>Restrictions on Use of Our Online Materials: All Online Materials on the Udimicom, Limited site, including, without limitation, text, software, names, logos, trademarks, service marks, trade names, images, photos, illustrations, audio clips, video clips, and music are copyrighted intellectual property. All usage rights are owned and controlled by Udimicom, Limited.</p>
    <p>You, the visitor, may download Online Materials for non-commercial, personal use only provided you:</p>
    <p>
      1) Retain all copyright, trademark and propriety notices
      <br>2) You make no modifications to the materials
      <br>3) You do not use the materials in a manner that suggests an association with any of our products, services, events or brands, and
      <br>4) you do not download quantities of materials to a database, server, or personal computer for reuse for commercial purposes. You may not, however, copy, reproduce, republish, upload, post, transmit or distribute Online Materials in any way or for any other purpose unless you get our written permission first. Neither may you add, delete, distort or misrepresent any content on the Udimicom, Limited site.</p>

    <p>Any attempts to modify any Online Material, or to defeat or circumvent our security features is prohibited. Everything you download, any software, plus all files, all images incorporated in or generated by the software, and all data accompanying it, is considered licensed to you by Udimicom, Limited or third-party licensors for your personal, non-commercial home use only. We do not transfer title of the software to you. That means that we retain full and complete title to the software and to all of the associated intellectual-property rights.</p>
    <p>You’re not allowed to redistribute or sell the material or to reverse-engineer, disassemble or otherwise convert it to any other form that people can use. Submitting Your Online Material to Us All remarks, suggestions, ideas, graphics, comments, or other information that you send to Udimicom, Limited through our site (other than information we promise to protect under our privacy policy becomes and remains our property, even if this agreement is later terminated. That means that we don’t have to treat any such submission as confidential. You can’t sue us for using ideas you submit. If we use them, or anything like them, we don’t have to pay you or anyone else for them.</p>
    <p>We will have the exclusive ownership of all present and future rights to submissions of any kind. We can use them for any purpose we deem appropriate to our Udimicom, Limited mission, without compensating you or anyone else for them. You acknowledge that you are responsible for any submission you make. This means that you (and not we) have full responsibility for the message, including its legality, reliability, appropriateness, originality, and copyright.</p>


    <h2 class="b-h2">Limitation of Liability</h2>
    <p>Udimicom, Limited will not be liable for any damages or injury that accompany or result from your use of any of its site. These include (but are not limited to) damages or injury caused by any: use of (or inability to use) the site use of (or inability to use) any site to which you hyperlink from our site failure of our site to perform in the manner you expected or desired error on our site omission on our site interruption of availability of our site defect on our site delay in operation or transmission of our site computer virus or line failure please note that we are not liable for any damages, including: damages intended to compensate someone directly for a loss or injury damages reasonably expected to result from a loss or injury (known in legal terms as “consequential damages.”) other miscellaneous damages and expenses resulting directly from a loss or injury (known in legal terms as “incidental damages.”) we are not liable even if we’ve been negligent or if our authorized representative has been advised of the possibility of such damages or both. Exception: certain state laws may not allow us to limit or exclude liability for these “incidental” or “consequential” damages. If you live in one of those states, the above limitation obviously would not apply which would mean that you might have the right to recover these types of damages. However, in any event, our liability to you for all losses, damages, injuries, and claims of any and every kind (whether the damages are claimed under the terms of a contract, or claimed to be caused by negligence or other wrongful conduct, or they’re claimed under any other legal theory) will not be greater than the amount you paid if anything to access our site.

    <h2 class="b-h2">Termination of this Agreement</h2>
    <p>This agreement is effective until terminated by either party. You may terminate this agreement at any time, by destroying all materials obtained from all Udimicom, Limited Web site, along with all related documentation and all copies and installations. Udimicom, Limited may terminate this agreement at any time and without notice to you, if, in its sole judgment, you breach any term or condition of this agreement. Upon termination, you must destroy all materials. In addition, by providing material on our Web site, we do not in any way promise that the materials will remain available to you. And Udimicom, Limited is entitled to terminate all or any part of any of its Web site without notice to you. Jurisdiction and Other Points to Consider If you use our site from locations outside of the United Kingdom, you are responsible for compliance with any applicable local laws.</p>


    <h2 class="b-h2">SPAM Zero Tolerance Policy</h2>
    <p>We take a zero tolerance stance against spam. Any user who sends out spam will have their account terminated with or without notice and without any refund.</p>
    <p>Sites advertised via SPAM (spamvertised) may not be hosted on our servers. Any account which results in our IP space being blacklisted will be immediately suspended or terminated.</p>
    <p>Udimicom, Limited reserves the right to require changes or disable as necessary any site that does not comply with its established policies, or to make any such modifications in an emergency at its sole discretion.</p>
    <p>Udimicom, Limited reserves the right to charge the holder of the account used to send any unsolicited e-mail a cleanup fee or any charges incurred for blacklist removal. This cost of the cleanup fee is entirely at the discretion of Udimicom, Limited.</p>

    <h1 class="b-h1">Refund Policy</h1>
    <p>Any payment that is not older than 30 days is refundable. We will issue a non-questions-asked refund after the first your message to support.</p>

    <h2 class="b-h2">Children</h2>
    <p>Udimicom, Limited does not knowingly collect or solicit Personally Identifiable Information from or about children under 13 except as permitted by law. If we discover we have received any information from a child under 13 in violation of this policy, we will delete that information immediately. If you believe Udimicom, Limited has any information from or about anyone under 13, please contact us at the address listed below.</p>

    <h2 class="b-h2">Changes to this Policy</h2>
    <p>Udimicom, Limited reserves the right to change this policy at any time. Please check this page periodically for changes. Your continued use of our site following the posting of changes to these terms will mean you accept those changes. Information collected prior to the time any change is posted will be used according to the rules and laws that applied at the time the information was collected.</p>

    <h2 class="b-h2">Content monitoring policy</h2>
    <p>Udimicom reserves the right to remove and permanently delete the content from the service with or without notice if it violates intellectual property rights. You may notify us of any user content that violates these terms by the email below.</p>

    <h2 class="b-h2">Contacting Us</h2>
    <p>The best and fastest way to contact us, is to create free account on the main page and submit help desk ticket via Help link at the top of any page.</p>

    <p>
      <strong>Udimicom, Limited</strong>
      <br>Spyrou Kyprianou 61, Sk House
      <br>4003 Limassol
      <br>Cyprus
      <br>con<span class="e-loath"> and </span>tact<span class="e-loath"> that. </span>@quwi.<span class="e-loath"> super </span>com
    </p>

  </div>
</template>

<script>
  export default {
    mounted () {
      window.scroll(0, 0)
    }
  }
</script>

<style lang="less" type="text/less">
    @import '~assets/css/mixins.less';
    @import '~assets/css/variables.less';
    @import '~assets/css/animation.less';
    @import '~assets/css/menu.less';
    @import '~assets/css/libs/load_awesome/load_awesome.less';

    .b-tos {
      width: 700px;
      margin: 20px auto;
      .e-loath {
        display: none;
      }
      h1 {
        text-align: center;
        color: #c33a24;
        font-size: 24px;
        padding: 15px 0;
      }
      h2 {
        color: #c33a24;
        font-size: 20px;
        padding: 25px 0 15px 0;
      }
      p {
        margin: 0 0 15px 0;
        line-height: 22px;
        text-align: justify;
      }
      ul {
        margin: 0;
        li {
          text-align: justify;
          margin: 0 0 15px 0;
          line-height: 22px;
        }
      }
    }
</style>
